#!/bin/sh

set -e

case "$1" in
   configure|upgrade)
	n4d-modules enable-plugin /etc/n4d/conf.d/MysqlManager || true
	;;
   abort-upgrade|abort-remove|abort-deconfigure)
	;;
  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac

#DEBHELPER#

exit 0
